#!/usr/bin/env bash
# This script displays information about subdomains

get_record_info() {
    local subdomain=$1
    local domain=$2
    dig_output=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print}')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            get_record_info "$sub" "$domain"
        done
    else
        get_record_info "$subdomain" "$domain"
    fi
}

main "$@"

