#!/usr/bin/env bash
# This script displays different messages based on loop iteration

# Counter
count=1

# Loop with while to display messages based on iteration
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done

