#!/usr/bin/env bash
# This script starts the 4-to_infinity_and_beyond process.

# Start the 4-to_infinity_and_beyond script in the background
./4-to_infinity_and_beyond &

# Display a message
echo "You can't stop me now!"

