#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Counter for hours
hour=0

# Loop with while to display hours and minutes
while [ $hour -lt 12 ]; do
    echo "Hour: $hour"
    
    # Counter for minutes
    minute=1
    
    # Loop with while to display minutes
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    
    ((hour++))
done

