#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
service nginx restart
ps auxff | grep ngin[x]
nc -z 0 8080

