#!/usr/bin/env bash
# This script connects to the server using SSH with the private key ~/.ssh/school and the user ubuntu.

# Connect to the server using SSH with the private key and username
ssh -i ~/.ssh/school -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@server01

