#!/usr/bin/env bash
# This script creates an RSA key pair.

# Define variables
KEY_NAME="school"
BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -f ~/.ssh/$KEY_NAME -N "$PASSPHRASE"

# Print success message
echo "RSA key pair generated successfully."

